[build-system]
requires = [
    "setuptools >=61.0.0",
    "wheel",
    "oldest-supported-numpy", 
    "packaging",
    "py-cpuinfo",
    "Cython ==0.29.35",
    "blosc2 ==2.2.6"
]
build-backend = "setuptools.build_meta"
