[build-system]
requires = [
    "setuptools ==65.5.1",
    "wheel",
    #"oldest-supported-numpy",
    "numpy ==1.25.2",
    "packaging",
    "py-cpuinfo",
    "Cython ==0.29.36",
    "blosc2 ==2.2.6"
]
build-backend = "setuptools.build_meta"
